-- ===================== Adding ADMIN =====================
INSERT INTO admin (id, name, password, username)VALUES (1, 'Neuro', '1234', 'admin')ON CONFLICT (id) DO NOTHING;

-- ===================== Adding Menu Items ===================== 
INSERT INTO public.menu_item(id, category, combination, description, is_available, name, dietitian_price, patient_price, staff_price, diet_type, time_slot)
VALUES
	(1, 'Liquid', null, null, true, 'Black tea', 12, 15, 12, 'Clear liquid', NULL),
	(2, 'Liquid', null, null, true, 'Tender coconut water', 12, 15, 12, 'Clear liquid', NULL),
	(3, 'Liquid', null, null, true, 'Rice water', 12, 15, 12, 'Clear liquid', NULL),
	(4, 'Liquid', null, null, true, 'Sago water', 12, 15, 12, 'Clear liquid', NULL),
	(5, 'Liquid', null, null, true, 'Barley water', 12, 15, 12, 'Clear liquid', NULL),
	(6, 'Liquid', null, null, true, 'Lemon juice', 12, 15, 12, 'Clear liquid', NULL),
	(7, 'Liquid', null, null, true, 'Rava water', 12, 15, 12, 'Clear liquid', NULL),
	(8, 'Liquid', null, null, true, 'Red rice water', 12, 15, 12, 'Clear liquid', NULL),
	(9, 'Liquid', null, null, true, 'RICE FEED', 12, 15, 12, 'Normal,ACITROM,CKD', NULL),
	(10, 'Liquid', null, null, true, 'VEGETABLE FEED', 12, 15, 12, 'Normal', NULL),
	(11, 'Liquid', null, null, true, 'GREEN FEED', 12, 15, 12, 'Normal', NULL),
	(12, 'Liquid', null, null, true, 'DHALL FEED', 12, 15, 12, 'Normal', NULL),
	(13, 'Liquid', null, null, true, 'MULTIGRAIN FEED', 12, 15, 12, 'Normal,DM,ACITROM', NULL),
	(14, 'Liquid', null, null, true, 'GREEN GRAM FEED', 12, 15, 12, 'Normal,DM', NULL),
	(15, 'Liquid', null, null, true, 'FRUIT JUICE', 12, 15, 12, 'Normal', NULL),
	(16, 'Liquid', null, null, true, 'BLACK GRAM FEED', 12, 15, 12, 'Normal', NULL),
	(17, 'Liquid', null, null, true, 'RAGI FEED', 12, 15, 12, 'Normal,DM,ACITROM', NULL),
	(18, 'Liquid', null, null, true, 'WHEAT FEED', 12, 15, 12, 'Normal,DM,ACITROM', NULL),
	(19, 'Liquid', null, null, true, 'RED RICE FEED', 12, 15, 12, 'Normal,ACITROM', NULL),
	(20, 'Liquid', null, null, true, 'MILK', 12, 15, 12, 'Normal,ACITROM', NULL),
	(21, 'Liquid', null, null, true, 'MILK WITHOUT SUGAR', 12, 15, 12, 'DM', NULL),
	(22, 'Liquid', null, null, true, 'WHEAT FEED', 12, 15, 12, 'DM', NULL),
	(23, 'Liquid', null, null, true, 'DHALL SOUP', 12, 15, 12, 'DM', NULL),
	(24, 'Liquid', null, null, true, 'GREEN SOUP', 12, 15, 12, 'DM', NULL),
	(33, 'Liquid', null, null, true, 'OATS FEED', 12, 15, 12, 'ACITROM', NULL),
	(35, 'Liquid', null, null, true, 'RAVA FEED', 12, 15, 12, 'ACITROM,CKD,CKD WITH ACITROM', NULL),
	(40, 'Liquid', null, null, true, 'D.MILK/SAGO FEED', 12, 15, 12, 'CKD', NULL),
	(42, 'Liquid', null, null, true, 'ORANGE JUICE', 12, 15, 12, 'CKD', NULL),
	(43, 'Liquid', null, null, true, 'DHALL WATER', 12, 15, 12, 'CKD', NULL),
	(45, 'Liquid', null, null, true, 'SAGO FEED', 12, 15, 12, 'CKD', NULL),
	(47, 'Liquid', null, null, true, 'BARLEY FEED', 12, 15, 12, 'CKD,CKD WITH ACITROM', NULL),
	(49, 'Liquid', null, null, true, 'SAGO FEED', 12, 15, 12, 'CKD,CKD WITH ACITROM', NULL),
	(59, 'Semi-Solid', null, null, true, 'IDLI', 12, 15, 12, 'NORMAL,ACITROM', NULL),
	(60, 'Semi-Solid', null, null, true, 'VARAGU PONGAL', 12, 15, 12, 'NORMAL,DM,ACITROM', NULL),
	(61, 'Semi-Solid', null, null, true, 'RAVA UPMA', 12, 15, 12, 'NORMAL', NULL),
	(62, 'Semi-Solid', null, null, true, 'RICE PORIDEGE', 12, 15, 12, 'NORMAL.CKD', NULL),
	(63, 'Semi-Solid', null, null, true, 'THINAI PONGAL', 12, 15, 12, 'NORMAL,DM,ACITROM', NULL),
	(64, 'Semi-Solid', null, null, true, 'OATS PORRDIGE', 12, 15, 12, 'NORMAL,ACITROM', NULL),
	(65, 'Semi-Solid', null, null, true, 'RAGI PORRDIGE', 12, 15, 12, 'NORMAL,DM,DM WITH CKD', NULL),
	(66, 'Semi-Solid', null, null, true, 'WHEAT RAVA IDLI', 12, 15, 12, 'DM,DM WITH CKD', NULL),
	(68, 'Semi-Solid', null, null, true, 'MULTIGRAIN PORRIDGE', 12, 15, 12, 'DM', NULL),
	(69, 'Semi-Solid', null, null, true, 'WHEAT RAVA UPMA', 12, 15, 12, 'DM', NULL),
	(72, 'Semi-Solid', null, null, true, 'SAMAI PONGAL', 12, 15, 12, 'DM', NULL),
	(73, 'Semi-Solid', null, null, true, 'RAVA UPMA', 12, 15, 12, 'CKD,DM WITH CKD', NULL),
	(74, 'Semi-Solid', null, null, true, 'SAGO IDLI', 12, 15, 12, 'CKD', NULL),
	(75, 'Semi-Solid', null, null, true, 'OATS UPMA', 12, 15, 12, 'CKD,DM WITH CKD,ACITROM', NULL),
	(77, 'Semi-Solid', null, null, true, 'SAGO UPMA', 12, 15, 12, 'CKD,DM WITH CKD,ACITROM', NULL),
	(78, 'Semi-Solid', null, null, true, 'OATS PORRDIGE', 12, 15, 12, 'CKD,DM WITH CKD', NULL),
	(99, 'Semi-Solid', null, null, true, 'SAMAI PONGAL', 12, 15, 12, 'ACITROM', NULL),	(100, 'Solid', null, null, true, 'SAMBAR RICE', 12, 15, 12, 'Normal,CKD WITH DM', NULL),
	(101, 'Solid', null, null, true, 'RASAM RICE', 12, 15, 12, 'Normal,CKD WITH DM', NULL),
	(102, 'Solid', null, null, true, 'CURD RICE', 12, 15, 12, 'Normal,CKD WITH DM', NULL),
	(103, 'Solid', null, null, true, 'DHALL WITH GHEE RICE', 12, 15, 12, 'Normal,CKD WITH DM', NULL),
	(104, 'Solid', null, null, true, 'BISMILLABATH', 12, 15, 12, 'Normal', NULL),
	(105, 'Solid', null, null, true, 'GREENGRAM DHALL RICE', 12, 15, 12, 'Normal', NULL),
	(106, 'Solid', null, null, true, 'KEERAI SADAM', 12, 15, 12, 'Normal', NULL),
	(107, 'Solid', null, null, true, 'VARAGU SAMBAR RICE', 12, 15, 12, 'DM', NULL),
	(108, 'Solid', null, null, true, 'THINAI SAMBAR RICE', 12, 15, 12, 'DM', NULL),
	(109, 'Solid', null, null, true, 'KUTHIRAIVALLI SAMBAR RICE', 12, 15, 12, 'DM', NULL),
	(110, 'Solid', null, null, true, 'SAMAI SAMBAR RICE', 12, 15, 12, 'DM', NULL),
	(111, 'Solid', null, null, true, 'BROWN RICE BISMILLABATH', 12, 15, 12, 'DM', NULL),
	(112, 'Solid', null, null, true, 'KAMBU SAMBAR SATHAM', 12, 15, 12, 'DM', NULL),
	(113, 'Solid', null, null, true, 'VARAGU KEERAI SADAM', 12, 15, 12, 'DM', NULL),
	(114, 'Solid', null, null, true, 'BUTTERMILK WITH WHITE RICE', 12, 15, 12, 'ACITROM', NULL),
	(115, 'Solid', null, null, true, 'SAGO SAMBAR RICE', 12, 15, 12, 'ACITROM,CKD', NULL),
	(116, 'Solid', null, null, true, 'BROWN RICE RASAM SATHAM', 12, 15, 12, 'ACITROM,CKD', NULL),
	(117, 'Solid', null, null, true, 'SAGO BAGALABATH', 12, 15, 12, 'ACITROM,CKD,CKD WITH DM', NULL),
	(118, 'Solid', null, null, true, 'SAGO RASAM RICE', 12, 15, 12, 'ACITROM,CKD,CKD WITH DM', NULL),
	(119, 'Solid', null, null, true, 'BUTTERMILK WITH WHITE RICE', 12, 15, 12, 'ACITROM', NULL),
	(120, 'Solid', null, null, true, 'SAGO SAMBAR RICE', 12, 15, 12, 'ACITROM', NULL),
	(126, 'Solid', null, null, true, 'BROWN RICE WITH DHALL AND GHEE', 12, 15, 12, 'CKD,CKD WITH DM', NULL),
	(212, 'Solid', null, 'Idli-3-4nos\nSambar - 1cup\nChutney - 1cup', true, 'IDLY', 12, 15, 12, 'Normal', NULL),
	(214, 'Solid', null, 'Pongal-150g-200g\nChutney-1cup\nSambar 1cup', true, 'PONGAL', 12, 15, 12, 'Normal', NULL),
	(215, 'Solid', null, 'Rava kichidi - 150-200g\nChutney - 1 cup\nSambar - 1 cup', true, 'RAVA KICHIDI', 12, 15, 12, 'Normal', NULL),
	(216, 'Solid', null, 'Dosa - 3-4 nos\nSambar - 1 cup\nChutney - 1 cup', true, 'DOSA', 12, 15, 12, 'Normal', NULL),
	(218, 'Solid', null, 'Idiyappam - 3-4 nos\nCoconut Milk - 1 cup\nVeg Kuruma - 1 cup', true, 'IDIYAPPAM', 12, 15, 12, 'Normal,CKD', NULL),
	(219, 'Liquid', null, 'Mushroom soup - 1 cup\n250ml', true, 'MUSHROOM SOUP', 12, 15, 12, 'Normal,ACITROM,DM',NULL),
	(223, 'Liquid', null, 'Drumstick soup - 1 cup\n250ml', true, 'DRUMSTICK SOUP', 12, 15, 12, 'Normal',NULL),
	(226, 'Solid', null, 'Rice - 150-200g\nChapatti - 1\nMixed Vegetable Poriyal - 1 cup\nSambar - 1 cup\nRasam - 1 cup\nButtermilk - 1 cup\nEgg - 1', true, 'LUNCH MEAL', 12, 15, 12, 'Normal,ACITROM,DM,CKD', NULL),
    (233, 'Solid', null, 'Cowpeas Sundal - 200g', true, 'COWPEAS SUNDAL', 12, 15, 12, 'Normal,ACITROM,DM', NULL),
    (234, 'Solid', null, 'Multigrain Sundal - 200g', true, 'MULTIGRAIN SUNDAL', 12, 15, 12, 'Normal,ACITROM,DM', NULL),
    (235, 'Solid', null, 'Green Peas Sundal - 200g', true, 'GREEN PEAS SUNDAL', 12, 15, 12, 'Normal,ACITROM,DM', NULL),
    (236, 'Solid', null, 'Horsegram Sundal - 200g', true, 'HORSEGRAM SUNDAL', 12, 15, 12, 'Normal,ACITROM,DM', NULL),
    (237, 'Solid', null, 'Beans Sundal - 200g', true, 'BEANS SUNDAL', 12, 15, 12, 'Normal,ACITROM,DM',NULL),
    (238, 'Solid', null, 'Chickpeas Sundal - 200g', true, 'CHICKPEAS SUNDAL', 12, 15, 12, 'Normal,ACITROM,,DM', NULL),
    (239, 'Solid', null, 'Green Gram Sundal - 200g', true, 'GREEN GRAM SUNDAL', 12, 15, 12, 'Normal,ACITROM,,DM', NULL),
    (240, 'Solid', null, 'Chapathi with Veg Kuruma - 1 cup\nChutney - 1 cup', true, 'CHAPATHI WITH VEG KURUMA', 12, 15, 12, 'Normal,DM', NULL),	(351, 'Solid', null, 'Chapathi with Veg Kuruma - 1 cup - Chutney - 1 cup', true, 'CHAPATHI WITH VEG KURUMA', 12, 15, 12, 'ACITROM', NULL),
	(352, 'Solid', null, 'Idli - 3-4 nos - Sambar - 1 cup - Chutney - 1 cup', true, 'IDLI', 12, 15, 12, 'ACITROM',  NULL),
	(353, 'Solid', null, 'Dosai - 1 - Sambar - 1 cup - Chutney - 1 cup', true, 'DOSAI', 12, 15, 12, 'ACITROM',  NULL),
	(354, 'Solid', null, 'Rava Kitchadi - 150-200g - Chutney - 1 cup - Sambar - 1 cup', true, 'RAVA KITCHADI', 12, 15, 12, 'ACITROM', NULL),
	(421, 'Solid', null, 'Ragi Dosa- 3-4 nos- Uppma- Sambar 1 cup- Chutney 1 cup', true, 'RAGI DOSAI WITH UPPMA', 12, 15, 12, 'DM',  NULL),
	(422, 'Solid', null, 'Varagu Pongal- 150-200g- Sambar 1 cup- Chutney 1 cup', true, 'VARAGU PONGAL', 12, 15, 12, 'DM',  NULL),
	(423, 'Solid', null, 'Multigrain Dosa- 3-4 nos- Sambar 1 cup- Chutney 1 cup', true, 'MULTIGRAIN DOSAI', 12, 15, 12, 'DM',  NULL),
	(424, 'Solid', null, 'Thinai Pongal- 150-200g- Sambar 1 cup- Chutney 1 cup', true, 'THINAI PONGAL', 12, 15, 12, 'DM',  NULL),
	(425, 'Solid', null, 'Wheat Rava Uppma- 150g- Sambar 1 cup- Chutney 1 cup', true, 'WHEAT RAVA UPPMA', 12, 15, 12, 'DM',  NULL),
	(426, 'Solid', null, 'Ragi Semiya- 150-200g- Sambar 1 cup- Chutney 1 cup', true, 'RAGI SEMIYA', 12, 15, 12, 'DM',  NULL),
	(427, 'Solid', null, 'Wheat Dosai- 3-4 nos- Sambar 1 cup- Chutney 1 cup', true, 'WHEAT DOSAI', 12, 15, 12, 'DM',  NULL),
	(432, 'Liquid', null, 'Drumstick soup- 1 cup- 250ml', true, 'DRUMSTICK SOUP', 12, 15, 12, 'DM', NULL),
	(449, 'Solid', null, 'Wheat Rava Idli- 3-4 nos- Sambar 1 cup- Chutney 1 cup', true, 'WHEAT RAVA IDLI', 12, 15, 12, 'DM',  NULL),
	(450, 'Solid', null, 'Chapathi- 3-4 nos- Veg Kuruma 1 cup- Chutney 1 cup', true, 'CHAPATHI WITH VEG KURUMA', 12, 15, 12, 'DM',  NULL),
	(452, 'Solid', null, 'Ragi Dosai- 3-4 nos- Sambar 1 cup- Chutney 1 cup', true, 'RAGI DOSAI', 12, 15, 12, 'DM',  NULL),
	(453, 'Solid', null, 'Wheat Rava Idli- 3-4 nos- Sambar 1 cup- Chutney 1 cup', true, 'WHEAT RAVA IDLI', 12, 15, 12, 'DM',  NULL),
	(456, 'Liquid', null, 'Black Tea 100ml', true, 'BLACK TEA', 12, 15, 12, 'CKD', NULL),
	(470, 'Liquid', NULL, 'Slim Milk Tea - 1 cup', TRUE, 'SLIM MILK TEA', 12, 15, 12, 'CKD', NULL),
	(477, 'Solid', NULL, 'Rava Idli - 3-4 nos, Sambar - 1 cup, Chutney - 1 cup', TRUE, 'RAVA IDLI', 12, 15, 12, 'CKD',  NULL),
	(479, 'Solid', NULL, 'Rava Uppma - 150-200g, Sambar - 1 cup, Chutney - 1 cup', TRUE, 'RAVA UPPMA', 12, 15, 12, 'CKD',  NULL),
	(480, 'Solid', NULL, 'Sago Dosai - 3-4 nos', TRUE, 'SAGO DOSAI', 12, 15, 12, 'CKD',  NULL),
	(481, 'Solid', NULL, 'Oats Uppma - 150-200g, Sambar - 1 cup, Chutney - 1 cup', TRUE, 'OATS UPPMA', 12, 15, 12,'CKD',NULL);